package com.example.wyrmprint.data.local

interface ComicItem {
    // Item id generated by API
    var id: Int

    // Comic title
    var title: String

    // Comic issue/number
    var episodeNumber: Int

    // Url to comic image
    var comicUrl: String
}